# Generated by Django 5.2.17 on 2026-10-07 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CvatIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cvat_user_id", models.PositiveIntegerField(unique=True)),
                ("cvat_username", models.CharField(blank=True, max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvat_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("annotator", "Annotator"),
                            ("reviewer", "Reviewer"),
                            ("qa_lead", "QA Lead"),
                            ("qc_admin", "QC Admin"),
                            ("super_admin", "Super Admin"),
                            ("product_owner", "Product Owner"),
                            ("data_model_owner", "Data/Model Owner"),
                        ],
                        max_length=32,
                    ),
                ),
                ("dataset_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role", "dataset_id"),
                        name="accounts_role_assignment_unique",
                        nulls_distinct=False,
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("dataset_id__isnull", False),
                            ("role__in", ["super_admin", "qc_admin"]),
                            _connector="OR",
                        ),
                        name="accounts_role_assignment_system_wide_roles",
                    ),
                ],
            },
        ),
    ]
