# Generated by Django 5.2.17 on 2026-10-08 17:32

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Định danh nhân sự ổn định do quản trị nội bộ cấp (HR/IT). Không cho phép người dùng tự khai báo hoặc tự sửa.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Thời điểm xác minh mapping. Null = chưa xác minh.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="SUPER_ADMIN/QC_ADMIN đã xác minh mapping này. PROTECT: không được xóa người xác minh khi còn mapping.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee_id"],
            },
        ),
        migrations.AddField(
            model_name="cvatidentity",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Liên kết tới EmployeeIdentity. Null = chưa đối soát; không được phép phê duyệt khi null (fail-closed). PROTECT: không được xóa EmployeeIdentity khi còn CvatIdentity trỏ tới.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cvat_identities",
                to="accounts.employeeidentity",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeidentity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("verified_at__isnull", True), ("verified_by__isnull", True)),
                    models.Q(("verified_at__isnull", False), ("verified_by__isnull", False)),
                    _connector="OR",
                ),
                name="accounts_employee_identity_verified_fields_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeidentity",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("employee_id"),
                name="accounts_employee_identity_employee_id_ci_unique",
            ),
        ),
    ]
