# Generated by Django 5.2.17 on 2026-10-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("runs", "0004_run_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="workunit",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
