/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Đặt cookie csrftoken
         * @description Không cần đăng nhập. Frontend gọi một lần trước POST /api/auth/login/.
         */
        get: operations["auth_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập, tạo session */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng xuất, huỷ session
         * @description Lease đang giữ không bị trả; nó hết hạn theo FR-REV-04.
         */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Người dùng, vai trò theo scope, identity mapping
         * @description Frontend dùng để guard route và ẩn menu theo vai trò. Ẩn menu chỉ là tiện ích;
         *     backend vẫn kiểm quyền ở mọi endpoint (FR-SEC-01).
         */
        get: operations["auth_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/workflow-permissions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ma trận phân quyền và quy tắc workflow
         * @description Cung cấp cấu hình ma trận phân quyền theo vai trò (7 vai trò) và các quy tắc workflow
         *     (anti-self-review, super admin override, separation of duties) phục vụ màn hình WorkflowPermissions.
         */
        get: operations["auth_workflow_permissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dataset trong scope người gọi
         * @description Đường dẫn đề xuất (rest-api.html §4.2); danh sách luôn lọc theo scope.
         */
        get: operations["datasets_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasets/{id}/tasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cây task/job CVAT của dataset để chọn phạm vi snapshot
         * @description Đọc qua adapter CVAT chỉ đọc (FR-SNP-01). Đường dẫn đề xuất (rest-api.html §4.2).
         */
        get: operations["datasets_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo snapshot cho một phạm vi (chạy nền) */
        post: operations["snapshots_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trạng thái, hash từng job, hash tổng, drift */
        get: operations["snapshots_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lịch sử QC Run
         * @description Đường dẫn đề xuất (rest-api.html §4.2).
         */
        get: operations["runs_list"];
        put?: never;
        /** Tạo QC Run trên snapshot locked và config version đã publish */
        post: operations["runs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trạng thái run, trạng thái từng engine, is_final */
        get: operations["runs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Huỷ run queued/running
         * @description Gọi lại khi run đã cancelled trả 200 (idempotent tự nhiên).
         */
        post: operations["runs_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/retry-failed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chạy lại các đơn vị failed của run partial
         * @description Idempotent theo work_unit.idempotency_key; không tạo candidate/issue trùng.
         */
        post: operations["runs_retry_failed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/ledger/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coverage ledger theo engine */
        get: operations["runs_ledger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{id}/ranking/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ranking frame theo s(f), có lọc
         * @description Người lập GT của tập đánh giá nhận 403 FORBIDDEN (FR-EVL-02, BR-10).
         *     Frame thiếu bằng chứng vẫn có trong danh sách, mang cờ missing_evidence (FR-RNK-06).
         */
        get: operations["runs_ranking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guidelines/rules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tra rule theo nhóm lỗi, lớp, cặp lớp
         * @description Không dùng retrieval ngữ nghĩa (FR-GDL-04). Mặc định guideline version mới nhất.
         */
        get: operations["guidelines_rules_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guidelines/mappings/": {
        parameters: { query?: never; header?: never; path?: never; cookie?: never; };
        get: operations["guidelines_mappings_list"];
        put?: never; post?: never; delete?: never; options?: never; head?: never; patch?: never; trace?: never;
    };
    "/api/guidelines/rules/{rule_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rule theo guideline version của snapshot */
        get: operations["guidelines_rules_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queues/{name}/next/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cấp lease frame kế tiếp
         * @description Mỗi reviewer giữ tối đa một lease (DEC-002/BLOCKER-008). Nếu đang giữ một lease còn hạn
         *     thì trả lại chính lease đó (tab thứ hai nhận cùng frame). Frame "đang dở" (incomplete)
         *     được ưu tiên trả về reviewer cũ trong cửa sổ giữ chỗ (TBD-09). Bỏ qua frame mà người gọi
         *     là assignee tại snapshot (FR-REV-03). Thiếu identity mapping → 403 IDENTITY_MAPPING_MISSING.
         */
        post: operations["queues_next"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leases/{id}/renew/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gia hạn lease
         * @description Chỉ người giữ lease; lease đã hết hạn hoặc của người khác → 409 LEASE_CONFLICT.
         */
        post: operations["leases_renew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{id}/issues/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue, evidence, trạng thái engine và rule của frame */
        get: operations["frames_issues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/frames/{id}/complete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đã review xong frame — trả lease, dừng effort
         * @description Cho phép khi mọi issue của frame đã có quyết định hoặc đang chờ phân xử (FR-REV-13),
         *     nếu không → 422 BUSINESS_RULE_UNMET kèm details.undecided_issue_ids.
         *     Gọi lại khi frame đã reviewed trả 200.
         */
        post: operations["frames_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "INVALID_CREDENTIALS" | "NOT_AUTHENTICATED" | "FORBIDDEN" | "OUT_OF_SCOPE" | "SELF_REVIEW_FORBIDDEN" | "SAME_REQUESTER_APPROVER" | "IDENTITY_MAPPING_MISSING" | "NOT_FOUND" | "LEASE_CONFLICT" | "INVALID_TRANSITION" | "REVISION_UNCHANGED" | "IDEMPOTENCY_KEY_REUSED" | "SCOPE_BUSY" | "ISSUE_EXISTS" | "BUSINESS_RULE_UNMET" | "INSUFFICIENT_SAMPLE";
        /**
         * @example {
         *       "code": "LEASE_CONFLICT",
         *       "message": "Lease đã hết hạn hoặc thuộc người khác",
         *       "request_id": "0b6f7c1e-3c55-4d43-9a43-3f0e1f6d2a10",
         *       "details": {}
         *     }
         */
        Error: {
            code: components["schemas"]["ErrorCode"];
            /** @description Thông báo tiếng Việt cho người dùng */
            message: string;
            /** @description Trùng header X-Request-ID của phản hồi; dùng để tra log và audit */
            request_id: string;
            /**
             * @description VALIDATION_ERROR: {"fields": {"<tên trường>": ["<lỗi>"]}}.
             *     INVALID_TRANSITION: {"from": "...", "event": "..."} và có thể drift_jobs.
             *     BUSINESS_RULE_UNMET ở frames_complete: {"undecided_issue_ids": [..]}.
             */
            details?: {
                [key: string]: unknown;
            };
        };
        LoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        /**
         * @description Vai trò theo SRS tab:rbac và đoạn dưới bảng (Product Owner, Data/Model Owner)
         * @enum {string}
         */
        Role: "annotator" | "reviewer" | "qa_lead" | "qc_admin" | "super_admin" | "product_owner" | "data_model_owner";
        RoleAssignment: {
            role: components["schemas"]["Role"];
            /** @description null nghĩa là toàn hệ thống (chỉ super_admin, qc_admin) */
            dataset_id: number | null;
        };
        Session: {
            user: {
                id: number;
                username: string;
                display_name: string;
            };
            roles: components["schemas"]["RoleAssignment"][];
            identity_mapping: {
                /**
                 * @description missing → mọi thao tác review/phân xử/verify bị từ chối (fail closed)
                 * @enum {string}
                 */
                status: "mapped" | "missing";
                cvat_user_id?: number | null;
            };
        };
        WorkflowPermissions: {
            matrix: components["schemas"]["WorkflowMatrixItem"][];
            rules: components["schemas"]["WorkflowRule"][];
            user_roles: components["schemas"]["RoleAssignment"][];
        };
        WorkflowMatrixItem: {
            function: string;
            roles: {
                annotator: string;
                reviewer: string;
                qa_lead: string;
                qc_admin: string;
                super_admin: string;
                product_owner: string;
                data_model_owner: string;
            };
        };
        WorkflowRule: {
            rule: string;
            name: string;
            description: string;
            enforced: boolean;
        };
        Dataset: {
            id: number;
            name: string;
            cvat_project_id: number;
            taxonomy_version?: string | null;
            guideline_version?: string | null;
        };
        CvatTask: {
            cvat_task_id: number;
            name: string;
            jobs: {
                cvat_job_id: number;
                assignee_cvat_user_id: number | null;
                frame_count?: number;
                /** Format: date-time */
                updated_date: string;
            }[];
        };
        /**
         * @description docs/04-api/state-machines.html §1
         * @enum {string}
         */
        SnapshotStatus: "pending" | "exporting" | "locked" | "failed";
        SnapshotCreate: {
            dataset_id: number;
            /** @description Rỗng cả hai danh sách nghĩa là toàn dataset */
            scope: {
                cvat_task_ids?: number[];
                cvat_job_ids?: number[];
            };
            note?: string;
        };
        SnapshotAccepted: {
            id: number;
            status: components["schemas"]["SnapshotStatus"];
        };
        Snapshot: {
            id: number;
            dataset_id: number;
            status: components["schemas"]["SnapshotStatus"];
            /** @enum {string|null} */
            failure_reason?: "drift_detected" | "export_error" | null;
            /**
             * @description SHA-256 tổng, có khi locked (FR-SNP-03)
             * @example sha256:5f1d…
             */
            revision_hash?: string | null;
            parent_snapshot_id: number | null;
            jobs: {
                cvat_job_id: number;
                job_hash: string | null;
                /** @description User LabelX của assignee tại snapshot qua identity mapping (FR-SNP-05) */
                assignee_user_id: number | null;
            }[];
            taxonomy_version?: string | null;
            guideline_version?: string | null;
            /** @description Shape không phải bounding box bị bỏ qua (FR-SNP-07) */
            out_of_scope_shapes?: number;
            drift_jobs: number[];
            created_by: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            locked_at?: string | null;
        };
        /**
         * @description docs/04-api/state-machines.html §2
         * @enum {string}
         */
        RunStatus: "queued" | "running" | "completed" | "partial" | "failed" | "cancelled";
        /** @enum {string} */
        EngineName: "schema" | "geometry" | "duplicate" | "detector" | "metric" | "vlm";
        /**
         * @description Trạng thái công khai (FR-AGG-05); không giá trị nào nghĩa là "đạt".
         *     Suy ra từ LedgerEntry theo quy tắc trong docs/04-api/engine-interface.html §3 (T-006,
         *     DEC-010); `checked` chỉ khi mọi đơn vị eligible đã completed.
         * @enum {string}
         */
        EngineStatus: "running" | "checked" | "partial" | "failed" | "not_checked";
        /**
         * @description SRS tab:enginestates
         * @enum {string}
         */
        NotCheckedReason: "disabled" | "no_model" | "no_reference" | "not_applicable" | "not_triggered";
        RunCreate: {
            snapshot_id: number;
            config_version_id: number;
            seed: number;
        };
        ModelArtifact: {
            name: string;
            version: string;
            checksum: string;
        };
        EngineRunStatus: {
            engine: components["schemas"]["EngineName"];
            status: components["schemas"]["EngineStatus"];
            reason?: components["schemas"]["NotCheckedReason"] | null;
            failed_units?: number;
        };
        Run: {
            id: number;
            snapshot_id: number;
            config_version_id: number;
            seed: number;
            status: components["schemas"]["RunStatus"];
            /** @description QC run cuối sau rework (FR-RWK-06) hoặc run gốc khi không có rework (BLOCKER-011) */
            is_final: boolean;
            /** @description Run gốc mà run cuối này nối verification về (DEC-005) */
            origin_run_id?: number | null;
            score_version?: string | null;
            model_artifact?: components["schemas"]["ModelArtifact"] | null;
            engines: components["schemas"]["EngineRunStatus"][];
            created_by: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            finished_at?: string | null;
        };
        /**
         * @description Coverage ledger của một engine trong một run (FR-AGG-04, T-006). Bất biến:
         *     total = completed + failed + pending + not_checked = eligible + excluded;
         *     excluded = not_checked_reasons.not_applicable + not_checked_reasons.not_triggered
         *     (đơn vị ngoài phạm vi áp dụng theo applicability_version; B-04 "mẫu số áp dụng", DEC-010);
         *     đơn vị failed, pending và not_checked do disabled/no_model/no_reference vẫn nằm trong eligible
         *     (không loại đơn vị lỗi khỏi mẫu số); coverage = completed / eligible, null khi eligible = 0.
         *     Khi excluded > 0, mọi nơi hiển thị coverage hoặc trạng thái engine phải hiện cảnh báo kèm số
         *     đơn vị bị loại theo lý do và applicability_version (engine-interface.html §4).
         */
        LedgerEntry: {
            engine: components["schemas"]["EngineName"];
            status: components["schemas"]["EngineStatus"];
            /** @description Engine bắt buộc cho coverage gate */
            required?: boolean;
            unit: components["schemas"]["EngineUnitKind"];
            /** @description Số đơn vị trong phạm vi snapshot của engine */
            total: number;
            /** @description Mẫu số coverage; gồm cả đơn vị failed, pending và not_checked chặn (disabled, no_model, no_reference) */
            eligible: number;
            /** @description Đơn vị ngoài phạm vi áp dụng (not_applicable + not_triggered), không vào mẫu số; > 0 thì phải hiện cảnh báo */
            excluded: number;
            /** @description Version quy tắc áp dụng đã dùng để loại đơn vị (EngineDescriptor.applicability_version) */
            applicability_version: string;
            completed: number;
            /** @description Đơn vị lỗi thực thi sau retry; vẫn trong mẫu số */
            failed: number;
            /** @description Đơn vị chưa có kết quả (pending, running, retrying) */
            pending: number;
            not_checked: number;
            /** @description Số đơn vị theo NotCheckedReason; tổng bằng not_checked */
            not_checked_reasons: {
                [key: string]: number;
            };
            /** @description completed / eligible; null khi eligible = 0 */
            coverage: number | null;
        };
        /**
         * @description Đơn vị áp dụng của engine (FR-AGG-04)
         * @enum {string}
         */
        EngineUnitKind: "frame" | "shape";
        /**
         * @description Trạng thái nội bộ của một đơn vị (không hiển thị). Map sang EngineStatus của đơn vị theo
         *     x-labelx-public-status, trùng kết quả tính từ ledger một đơn vị; trạng thái engine tổng hợp
         *     luôn tính từ LedgerEntry (engine-interface.html §3).
         * @enum {string}
         */
        EngineUnitOutcome: "pending" | "running" | "retrying" | "completed" | "failed" | "not_checked";
        /**
         * @description Trạng thái điều phối của engine trong run (orchestrator, không hiển thị). Không map trực
         *     tiếp sang EngineStatus: trạng thái hiển thị luôn tính từ LedgerEntry
         *     (engine-interface.html §3); x-labelx-terminal là các giá trị mà engine đã dừng.
         * @enum {string}
         */
        EngineInternalState: "queued" | "running" | "retrying" | "succeeded" | "partially_succeeded" | "failed" | "cancelled" | "disabled" | "model_unavailable" | "reference_unavailable" | "not_applicable";
        /** @description Đăng ký engine với orchestrator; thêm engine mới chỉ cần descriptor + worker (NFR-13) */
        EngineDescriptor: {
            name: components["schemas"]["EngineName"];
            /** @description Version code engine, ghi vào run (FR-ENG-01) */
            version: string;
            unit: components["schemas"]["EngineUnitKind"];
            /** @description Engine bắt buộc cho coverage gate */
            required: boolean;
            /** @description Thiếu model artifact thì engine Not checked (no_model) */
            needs_model: boolean;
            /** @description Thiếu GT/reference thì engine Not checked (no_reference) */
            needs_reference: boolean;
            /** @description Version quy tắc chọn đơn vị áp dụng; đơn vị ngoài phạm vi ghi not_applicable */
            applicability_version: string;
        };
        /** @description Cấu hình engine có version, nằm trong config version của run */
        EngineConfig: {
            engine: components["schemas"]["EngineName"];
            /** @description Version cấu hình (ngưỡng có version, FR-ENG-07) */
            version: string;
            /** @description false → mọi đơn vị not_checked với lý do disabled */
            enabled: boolean;
            /** @description Tham số riêng engine (ngưỡng IoU, τ_E1, τ_E2…) */
            params: {
                [key: string]: unknown;
            };
        };
        /** @description Một đơn vị áp dụng; shape định danh qua namespace cvat_shape (DEC-005) */
        EngineUnitRef: {
            kind: components["schemas"]["EngineUnitKind"];
            frame: components["schemas"]["FrameKey"];
            /** @description Bắt buộc khi kind = shape */
            object?: components["schemas"]["ObjectRef"] | null;
        };
        /** @description Một shard công việc gửi cho engine */
        EngineInput: {
            /** @description Băm của (snapshot, engine, config, model, shard); retry không tạo candidate trùng (FR-AGG-02) */
            idempotency_key: string;
            run_id: number;
            snapshot_id: number;
            engine: components["schemas"]["EngineName"];
            engine_version: string;
            config: components["schemas"]["EngineConfig"];
            model_artifact?: components["schemas"]["ModelArtifact"] | null;
            seed: number;
            shard_index: number;
            units: components["schemas"]["EngineUnitRef"][];
        };
        /** @description Nghi vấn do engine sinh; bất biến sau khi ghi, khác Issue (FR-AGG-01) */
        Candidate: {
            engine: components["schemas"]["EngineName"];
            engine_version: string;
            family: components["schemas"]["IssueFamily"];
            severity?: components["schemas"]["Severity"] | null;
            frame: components["schemas"]["FrameKey"];
            anchor: components["schemas"]["Anchor"];
            evidence: components["schemas"]["Evidence"];
        };
        /** @description Kết quả cuối của một đơn vị trong shard */
        EngineUnitResult: {
            unit: components["schemas"]["EngineUnitRef"];
            /**
             * @description Giá trị kết thúc của EngineUnitOutcome
             * @enum {string}
             */
            outcome: "completed" | "failed" | "not_checked";
            /** @description Bắt buộc khi outcome = not_checked */
            not_checked_reason?: components["schemas"]["NotCheckedReason"] | null;
            /** @description Lỗi thực thi khi outcome = failed (timeout, ảnh hỏng, worker lỗi); không chứa secret */
            error?: string | null;
            attempts: number;
        };
        /** @description Kết quả một shard; orchestrator ghi candidates và cập nhật ledger trong cùng transaction (FR-AGG-06) */
        EngineOutput: {
            idempotency_key: string;
            engine: components["schemas"]["EngineName"];
            engine_version: string;
            candidates: components["schemas"]["Candidate"][];
            unit_results: components["schemas"]["EngineUnitResult"][];
        };
        RankedFrame: {
            frame_id: number;
            frame_key?: components["schemas"]["FrameKey"];
            rank: number;
            /** @description s(f) theo score_version của run */
            score: number;
            queue?: components["schemas"]["QueueName"];
            review_state: components["schemas"]["FrameReviewState"];
            missing_evidence: boolean;
            /** @description Số issue theo IssueFamily */
            issue_counts: {
                [key: string]: number;
            };
            lease_holder_user_id?: number | null;
        };
        GuidelineRule: {
            /** @example VEH-03 */
            rule_id: string;
            section: string;
            content: string;
            guideline_version: string;
        };
        RuleMapping: {
            error_group: string;
            class_name: string;
            paired_class: string;
            rule_id: string;
            guideline_version: string;
        };
        /** @enum {string} */
        QueueName: "risk" | "random";
        /**
         * @description docs/04-api/state-machines.html §4; incomplete là "đang dở" (BLOCKER-008)
         * @enum {string}
         */
        FrameReviewState: "unreviewed" | "in_review" | "incomplete" | "reviewed" | "awaiting_followup" | "completed";
        /**
         * @description docs/04-api/state-machines.html §3
         * @enum {string}
         */
        IssueState: "pending_review" | "in_review" | "confirmed" | "rejected" | "escalated" | "fix_pending" | "recheck_pending" | "resolved" | "reopened";
        /**
         * @description E1 thiếu box, E2 sai lớp, E3 trùng box; structural là cảnh báo cấu trúc có rule ID
         * @enum {string}
         */
        IssueFamily: "E1" | "E2" | "E3" | "structural";
        /** @enum {string} */
        IssueOrigin: "engine" | "reviewer";
        /** @enum {string} */
        Severity: "critical" | "medium" | "minor";
        QueueNextRequest: {
            run_id: number;
        };
        Lease: {
            id: number;
            frame_id: number;
            holder_user_id: number;
            /**
             * Format: date-time
             * @description Thời hạn lease là TBD-09, đo trong pilot rồi chốt
             */
            expires_at: string;
        };
        /** @description Định danh frame ổn định qua snapshot (DEC-005) */
        FrameKey: {
            cvat_task_id: number;
            frame_number: number;
        };
        FrameSummary: {
            id: number;
            run_id: number;
            frame_key: components["schemas"]["FrameKey"];
            cvat_job_id?: number;
            rank?: number | null;
            review_state: components["schemas"]["FrameReviewState"];
            missing_evidence: boolean;
            /** Format: uri */
            image_url?: string;
            width?: number;
            height?: number;
            /**
             * Format: uri
             * @description Mở đúng job và frame trên CVAT (FR-SNP-08, FR-REV-12)
             */
            cvat_deep_link?: string;
        };
        LeaseGrant: {
            lease: components["schemas"]["Lease"];
            frame: components["schemas"]["FrameSummary"];
            /** @description true khi trả lại lease đang giữ hoặc frame incomplete của chính reviewer */
            resumed?: boolean;
        };
        /** @description Toạ độ pixel gốc của ảnh */
        BBox: {
            x1: number;
            y1: number;
            x2: number;
            y2: number;
        };
        /**
         * @description Định danh đối tượng qua revision (DEC-005): namespace nguồn + id trong namespace đó.
         *     cvat_shape: id shape CVAT (ổn định khi annotator sửa shape; xoá rồi vẽ lại là đối tượng mới).
         *     detector: dự đoán của một run, id = "<run_id>:<index>" (không ổn định qua run).
         *     reviewer_region: vùng reviewer vẽ, id = UUID do server cấp.
         */
        ObjectRef: {
            /** @enum {string} */
            namespace: "cvat_shape" | "detector" | "reviewer_region";
            id: string;
        };
        /** @description Neo issue theo DEC-006 và SRS tab:anchors; kind quyết định trường nào bắt buộc */
        Anchor: {
            /** @enum {string} */
            kind: "prediction_region" | "annotation" | "annotation_cluster" | "annotation_rule" | "manual_object" | "manual_region";
            objects: components["schemas"]["ObjectRef"][];
            rule_id?: string | null;
            bbox?: components["schemas"]["BBox"] | null;
            /** @description Version quy tắc tạo neo, đi cùng policy gộp (FR-RNK-12) */
            policy_version: string;
        };
        /** @description Liên kết lineage (DEC-005) */
        IssueLink: {
            /**
             * @description recurrence_of — run cuối gặp lại cùng neo (khớp ObjectRef cvat_shape).
             *     suggested_recurrence_of — chỉ khớp bằng fallback hình học; chỉ để gợi ý.
             * @enum {string}
             */
            kind: "recurrence_of" | "suggested_recurrence_of";
            issue_id: number;
            run_id?: number;
        };
        Evidence: {
            engine: components["schemas"]["EngineName"];
            rule_id?: string | null;
            expected?: string | null;
            actual?: string | null;
            prediction_bbox?: components["schemas"]["BBox"] | null;
            prediction_class?: string | null;
            confidence?: number | null;
            iou?: number | null;
        };
        Issue: {
            id: number;
            family: components["schemas"]["IssueFamily"];
            origin: components["schemas"]["IssueOrigin"];
            state: components["schemas"]["IssueState"];
            anchor: components["schemas"]["Anchor"];
            /** @description Số lỗi đếm cho issue theo tab:anchors (E3 cụm m box → m−1) */
            n_i: number;
            q_i?: number | null;
            severity?: components["schemas"]["Severity"] | null;
            rule_ids?: string[];
            evidence: components["schemas"]["Evidence"][];
            links: components["schemas"]["IssueLink"][];
        };
        FrameIssues: {
            frame: components["schemas"]["FrameSummary"];
            guideline_version?: string | null;
            engines: components["schemas"]["EngineRunStatus"][];
            issues: components["schemas"]["Issue"][];
        };
        FrameCompleteRequest: {
            lease_id: number;
        };
        PaginatedDatasetList: {
            next?: string | null;
            previous?: string | null;
            results: components["schemas"]["Dataset"][];
        };
        PaginatedRunList: {
            next?: string | null;
            previous?: string | null;
            results: components["schemas"]["Run"][];
        };
        PaginatedRankedFrameList: {
            next?: string | null;
            previous?: string | null;
            results: components["schemas"]["RankedFrame"][];
        };
        PaginatedGuidelineRuleList: {
            next?: string | null;
            previous?: string | null;
            results: components["schemas"]["GuidelineRule"][];
        };
        PaginatedRuleMappingList: {
            next?: string | null;
            previous?: string | null;
            results: components["schemas"]["RuleMapping"][];
        };
    };
    responses: {
        /** @description Dữ liệu không hợp lệ (VALIDATION_ERROR, INVALID_CREDENTIALS) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Chưa đăng nhập (NOT_AUTHENTICATED), không có quyền (FORBIDDEN), ngoài scope (OUT_OF_SCOPE),
         *     self-review (SELF_REVIEW_FORBIDDEN), tách nhiệm vụ (SAME_REQUESTER_APPROVER),
         *     thiếu identity mapping (IDENTITY_MAPPING_MISSING). Được ghi audit.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Không tìm thấy (NOT_FOUND) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Xung đột trạng thái (LEASE_CONFLICT, INVALID_TRANSITION, REVISION_UNCHANGED,
         *     IDEMPOTENCY_KEY_REUSED, SCOPE_BUSY, ISSUE_EXISTS). Được ghi audit.
         */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Không đủ điều kiện nghiệp vụ (BUSINESS_RULE_UNMET, INSUFFICIENT_SAMPLE) */
        Unprocessable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: number;
        /** @description Con trỏ trang từ trường next/previous (CursorPagination, PAGE_SIZE=50) */
        Cursor: string;
        /**
         * @description UUID do client sinh. Cùng key + cùng body → trả lại phản hồi cũ; cùng key + body khác →
         *     409 IDEMPOTENCY_KEY_REUSED (rest-api.html §3). Mức bắt buộc chờ Tech Lead xác nhận.
         */
        IdempotencyKey: string;
        /** @description Guideline version tag; bỏ trống là bản mới nhất. Workspace truyền version của snapshot. */
        GuidelineVersion: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã đặt cookie csrftoken */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Đăng nhập thành công; trả session hiện tại */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã đăng xuất (gọi lại khi đã đăng xuất cũng trả 204) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    auth_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session hiện tại */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    auth_workflow_permissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ma trận phân quyền và quy tắc workflow */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowPermissions"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    datasets_list: {
        parameters: {
            query?: {
                /** @description Con trỏ trang từ trường next/previous (CursorPagination, PAGE_SIZE=50) */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trang dataset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDatasetList"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    datasets_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task và job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CvatTask"][];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    snapshots_create: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description UUID do client sinh. Cùng key + cùng body → trả lại phản hồi cũ; cùng key + body khác →
                 *     409 IDEMPOTENCY_KEY_REUSED (rest-api.html §3). Mức bắt buộc chờ Tech Lead xác nhận.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotCreate"];
            };
        };
        responses: {
            /** @description Đã nhận; theo dõi bằng GET /api/snapshots/{id}/ */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    snapshots_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    runs_list: {
        parameters: {
            query?: {
                dataset?: number;
                snapshot?: number;
                /** @description Con trỏ trang từ trường next/previous (CursorPagination, PAGE_SIZE=50) */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trang run, mới nhất trước */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRunList"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    runs_create: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description UUID do client sinh. Cùng key + cùng body → trả lại phản hồi cũ; cùng key + body khác →
                 *     409 IDEMPOTENCY_KEY_REUSED (rest-api.html §3). Mức bắt buộc chờ Tech Lead xác nhận.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Run ở trạng thái queued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
    runs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    runs_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run sau khi huỷ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    runs_retry_failed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run quay lại running */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    runs_ledger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một dòng mỗi engine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerEntry"][];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    runs_ranking: {
        parameters: {
            query?: {
                queue?: components["schemas"]["QueueName"];
                family?: components["schemas"]["IssueFamily"];
                origin?: components["schemas"]["IssueOrigin"];
                review_state?: components["schemas"]["FrameReviewState"];
                /** @description Con trỏ trang từ trường next/previous (CursorPagination, PAGE_SIZE=50) */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trang frame theo rank tăng dần */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRankedFrameList"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    guidelines_rules_list: {
        parameters: {
            query?: {
                /** @description Guideline version tag; bỏ trống là bản mới nhất. Workspace truyền version của snapshot. */
                version?: components["parameters"]["GuidelineVersion"];
                family?: components["schemas"]["IssueFamily"];
                class_name?: string;
                paired_class?: string;
                /** @description Con trỏ trang từ trường next/previous (CursorPagination, PAGE_SIZE=50) */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trang rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGuidelineRuleList"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    guidelines_rules_retrieve: {
        parameters: {
            query?: {
                /** @description Guideline version tag; bỏ trống là bản mới nhất. Workspace truyền version của snapshot. */
                version?: components["parameters"]["GuidelineVersion"];
            };
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuidelineRule"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    guidelines_mappings_list: {
        parameters: {
            query?: {
                version?: components["parameters"]["GuidelineVersion"];
                family?: components["schemas"]["IssueFamily"];
                class_name?: string;
                paired_class?: string;
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never; path?: never; cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: { headers: { [name: string]: unknown }; content: { "application/json": components["schemas"]["PaginatedRuleMappingList"] } };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    queues_next: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: components["schemas"]["QueueName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueueNextRequest"];
            };
        };
        responses: {
            /** @description Lease và frame */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaseGrant"];
                };
            };
            /** @description Hàng đợi hết frame phù hợp */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Unprocessable"];
        };
    };
    leases_renew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lease với expires_at mới */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lease"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    frames_issues: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Frame và issue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameIssues"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    frames_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrameCompleteRequest"];
            };
        };
        responses: {
            /** @description Frame sau khi hoàn tất review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameSummary"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Unprocessable"];
        };
    };
}
