/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/guidelines/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách guideline version
         * @description Trả danh sách các phiên bản guideline đã nạp vào hệ thống. Yêu cầu đăng nhập (FR-GDL-04, FR-SEC-01).
         */
        get: operations["guideline_version_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guidelines/rules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tra rule theo nhóm lỗi/lớp
         * @description Trả danh sách rule theo ánh xạ (error_group, class_name, paired_class). Có thể kết hợp nhiều filter. Không truyền filter → trả tất cả rule. Không dùng RAG (FR-GDL-04).
         */
        get: operations["guideline_rule_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/guidelines/rules/{rule_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tra rule theo rule ID
         * @description Trả thông tin một rule theo rule_id. Dùng query param version để chọn phiên bản; mặc định là phiên bản mới nhất. Trả 404 nếu rule_id không tồn tại (09-interfaces.tex §apierrors).
         */
        get: operations["guideline_rule_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Hợp đồng lỗi dùng chung của API LabelX. */
        ErrorResponse: {
            code: string;
            message: string;
            /** Format: uuid */
            request_id: string;
        };
        GuidelineRule: {
            /** @description Ví dụ: VEH-01 */
            rule_id: string;
            /** @description Ví dụ: §2.1 */
            section: string;
            /** @description Nội dung trích đoạn của rule */
            content: string;
            readonly guideline_version: string;
        };
        /** @description Envelope thực tế của API danh sách rule. */
        GuidelineRuleListResponse: {
            count: number;
            results: components["schemas"]["GuidelineRule"][];
        };
        GuidelineVersion: {
            /** @description Ví dụ: v1 */
            version_tag: string;
            /** @description Tên hiển thị cho phiên bản */
            name: string;
            /** Format: date-time */
            readonly loaded_at: string;
        };
        /** @description Envelope thực tế của API danh sách guideline version. */
        GuidelineVersionListResponse: {
            count: number;
            results: components["schemas"]["GuidelineVersion"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    guideline_version_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuidelineVersionListResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    guideline_rule_list: {
        parameters: {
            query?: {
                /** @description Tên lớp: car, truck, … */
                class_name?: string;
                /** @description Nhóm lỗi: E1, E2, E3 */
                error_group?: string;
                /** @description Lớp cặp: truck */
                paired_class?: string;
                /** @description version_tag, mặc định latest */
                version?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuidelineRuleListResponse"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    guideline_rule_retrieve: {
        parameters: {
            query?: {
                /** @description version_tag, mặc định latest */
                version?: string;
            };
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuidelineRule"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
