#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'../..');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(plan){
const phases=plan.phases.map(p=>`<tr><td>${esc(p.id)}</td><td>${esc(p.title)}</td><td>${esc(p.scope)}</td><td>${esc(p.dependencies.join(', ')||'—')}</td><td>${esc(p.source)}</td><td>${plan.cases.filter(c=>c.phase===p.id&&c.implementation==='implemented').length}/${plan.cases.filter(c=>c.phase===p.id).length} ca đã có mã; chưa xác nhận chạy đạt</td></tr>`).join('');
const rows=plan.cases.map(c=>`<tr data-phase="${c.phase}" data-state="${c.implementation}" data-level="${c.level}"><td>${c.id}</td><td>${c.phase}<br>${c.level}</td><td>${esc(c.scenario)}</td><td>${esc(c.expected)}</td><td>${esc(c.fixtures)}</td><td>${esc(c.requirements.join(', '))}<small>Ma trận test; SRS 06-functional/07-evaluation/08-nonfunctional, hoặc B/T/H theo mã.</small></td><td>${c.implementation==='implemented'?'Có mã test, cần chạy CI':'Chưa viết test'}${c.test_nodeid?'<small>'+esc(c.test_nodeid)+'</small>':''}</td></tr>`).join('');
return `<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LabelX — CI/CD và kiểm thử toàn bộ giai đoạn</title><style>body{margin:0;background:#f6f6f6;color:#222;font:14px/1.5 system-ui,Arial}main{max-width:1500px;margin:auto;padding:24px}section,header{background:white;border:1px solid #ccc;padding:20px;margin-bottom:18px}h1{font-size:25px}h2{font-size:19px}h3{font-size:15px}p{margin:8px 0}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #ccc;padding:8px;text-align:left;vertical-align:top}th{background:#eee}small{display:block;color:#555;margin-top:4px}a{color:inherit}code,pre{font-family:Consolas,monospace}pre{white-space:pre-wrap;border:1px solid #ccc;padding:12px}label{display:inline-block;margin:8px}select,button{font:inherit;padding:6px;border:1px solid #888;background:white}tr[hidden]{display:none}.scroll{overflow:auto}.cases{min-width:1100px}.toolbar{display:flex;flex-wrap:wrap;align-items:center}.blocked{color:#962929}.warning{color:#80520c}@page{size:A4 landscape;margin:12mm}@media print{body{background:white}main{padding:0}header,section{border:0;padding:0;margin:0 0 6mm}table{font-size:8pt}th,td{padding:4px}.toolbar{display:none}.scroll{overflow:visible}.cases{min-width:0}thead{display:table-header-group}tr{break-inside:avoid}tr[hidden]{display:table-row!important}h2{break-after:avoid}}</style></head><body><main>
<header><h1>CI/CD và kiểm thử toàn bộ giai đoạn LabelX</h1><p>Thiết kế kiểm thử và workflow khung, dựa trên stack DEC-001 và các quyết định đã chốt. Không tự triển khai sản phẩm hoặc mở rộng scope SRS M13.</p></header>
<section><h2>1. Kết luận</h2><ol><li>${plan.phases.length} nhóm giai đoạn và ${plan.cases.length} ca kiểm thử, có truy vết R-01–R-07/FR/AC/NFR.</li><li>Hiện chỉ một ca nghiệp vụ scaffold có mã smoke OpenAPI; chưa có adapter/engine/review/ranking, frontend chưa có test runner. Lint/build không thay E2E.</li><li>CI chạy trên PR/main: framework, lint/types, migration/schema, PostgreSQL smoke và Next build. Pipeline chưa có run GitHub thực trong workspace này.</li><li>Gate từ chối test chưa bind, zero/all-skipped, commit/provenance sai, policy/reference TBD. Kết quả dự kiến của phase chưa xây là <b class="blocked">BLOCKED</b>, không phải pass.</li><li>CD chưa có target/hook/approval môi trường; scaffold xanh không cho deploy MVP hoặc phát hành Dataset.</li></ol><small>Nguồn: src/backend/tests/test_smoke.py; src/frontend/package.json; DEC-001; test-matrix.json; .github/workflows/*.yml. Mã kiểm cổng CI có bộ test riêng, không tính là test nghiệp vụ.</small></section>
<section><h2>2. Luồng CI/CD</h2><p>PR → CI/checks → build artifact theo commit → phase tests/reference/evaluation → review QA → staging smoke/migration rehearsal → approval → production hook → smoke/rollback.</p><p>Deployment phần mềm khác phát hành Dataset. M13 chỉ hiển thị gate (SRS FR-GTE-04). RAG/Temporal/Classifier/full release sau MVP phải có scope được duyệt; VLM pilot còn TBD-08 trong SRS dự thảo.</p><table><thead><tr><th>Workflow</th><th>Khi chạy</th><th>Nhiệm vụ</th><th>Điều kiện/chặn</th></tr></thead><tbody><tr><td>ci.yml</td><td>PR/push main/manual</td><td>Kiểm scaffold/code, schema, lockfile, lint/types/build; JUnit và artifact</td><td>Không credentials CVAT/model; test thực tế lỗi thì không cho qua</td></tr><tr><td>phase-testing.yml</td><td>Manual main, runner nội bộ</td><td>Một phase hoặc toàn MVP; dependency receipt và policy</td><td>Thiếu test/reference/approval → BLOCKED</td></tr><tr><td>cd.yml</td><td>Manual main, environment approval</td><td>Verify CI + test cùng SHA, promote artifact, hook/smoke/rollback</td><td>Target/hook/evidence chưa đủ → không deploy</td></tr></tbody></table><small>Nguồn: docs/08-devops/ci-cd.md; GitHub environment settings phải cấu hình ngoài YAML.</small></section>
<section><h2>3. Giai đoạn và phụ thuộc</h2><div class="scroll"><table><thead><tr><th>Mã</th><th>Giai đoạn</th><th>Phạm vi</th><th>Phụ thuộc</th><th>Nguồn</th><th>Mức có mã test</th></tr></thead><tbody>${phases}</tbody></table></div><p class="warning">SRS LaTeX v1.0 vẫn ghi “bản đề xuất để duyệt”; FR/AC/NFR là nguồn thiết kế test, không tự đổi governance intake hoặc chốt TBD.</p></section>
<section><h2>4. Ma trận ca kiểm thử</h2><div class="toolbar"><label>Giai đoạn <select id="phase"><option value="">Tất cả</option>${plan.phases.map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join('')}</select></label><label>Trạng thái <select id="state"><option value="">Tất cả</option><option value="implemented">Có mã</option><option value="planned">Chưa viết</option></select></label><label>Tầng <select id="level"><option value="">Tất cả</option>${[...new Set(plan.cases.map(c=>c.level))].map(l=>`<option>${l}</option>`).join('')}</select></label><span id="count" role="status">${plan.cases.length}/${plan.cases.length} ca</span><button id="print">In A4</button></div><div class="scroll"><table class="cases"><thead><tr><th>Mã</th><th>Phase/tầng</th><th>Tình huống</th><th>Kết quả cần kiểm</th><th>Fixture/phụ thuộc</th><th>Yêu cầu/nguồn</th><th>Trạng thái mã</th></tr></thead><tbody>${rows}</tbody></table></div></section>
<section><h2>5. Dữ liệu, accuracy và kiểm thử thực tế</h2><p>PR dùng ảnh/annotation tổng hợp và mock/stub; không báo accuracy thật từ fixture. PostgreSQL/worker/Object Storage thật cần cho transaction/retry; eager task hoặc SQLite không chứng minh hệ phân tán.</p><p>Reference/held-out/policy/model/score phải có version và scope; chống giao video/train/guideline cases. Policy example có null và draft nên không dùng nghiệm thu. KPI engine tách reviewer agreement; AC-08/09 và latency vẫn BLOCKED khi TBD liên quan chưa chốt.</p><small>Nguồn: T mục 6–8; SRS FR-EVL-01…16, AC-08/09, NFR-01…03; quyết định B-05/B-14/B-20.</small></section>
<section><h2>6. Cổng CI/CD và bằng chứng</h2><p>Receipt mỗi phase lưu commit, hash plan, danh sách case và hash JUnit. Gate yêu cầu test không skip, đủ case, dependency passed và cùng commit. CD chỉ nhận CI/phase workflow success từ main, cùng SHA; không nhận PR run hoặc report cũ.</p><p>GitHub environment cần required reviewers/prevent self-review; bảo vệ main và runner dữ liệu. Cơ chế kiểm receipt không thay QA độc lập hoặc quyết định phê duyệt. Không log/upload ảnh, token, held-out hay prompt riêng.</p><small>Nguồn: scripts/ci/quality-gate.cjs; CI/CD workflows; AGENT.md; <a href="https://docs.github.com/en/actions/reference/workflows-and-actions/deployments-and-environments">GitHub environments</a>.</small></section>
<section><h2>7. Lệnh và tình trạng xác minh</h2><pre>node --test scripts/ci/tests/*.test.cjs
node scripts/ci/quality-gate.cjs validate-plan
node scripts/ci/render-plan.cjs --check
node scripts/ci/quality-gate.cjs run --phase scaffold
node scripts/ci/quality-gate.cjs run --phase p0_snapshot</pre><p>Scaffold run cần uv/Python/PostgreSQL. p0_snapshot hiện phải báo BLOCKED vì chưa có ca implemented. Chi tiết evidence local và hạn chế môi trường ở báo cáo implementation trong .agent/reports/implementation/; không mặc định kết quả kiểm ở đây là một CI run GitHub.</p></section>
<section><h2>8. Việc còn cần để kích hoạt toàn bộ</h2><ul><li>Git remote/provider/main protection và environments/runner thật.</li><li>Implement adapter/engine/ranking/review/evaluation; viết và bind từng test đã thiết kế.</li><li>Chọn runner browser theo DEC-001; UI/E2E phải có test thật.</li><li>Reference/model artifact và evaluation policy đã phê duyệt; không tự đặt KPI threshold.</li><li>Deployment target và các hook staging/production/smoke/rollback; diễn tập migration/backup trước production.</li></ul><p>Mọi nhóm sau MVP giữ trạng thái planned tới khi scope được duyệt và phụ thuộc đủ.</p></section>
</main><script>function filter(){const p=document.getElementById('phase').value,s=document.getElementById('state').value,l=document.getElementById('level').value;let n=0;document.querySelectorAll('tr[data-phase]').forEach(r=>{r.hidden=!!((p&&r.dataset.phase!==p)||(s&&r.dataset.state!==s)||(l&&r.dataset.level!==l));if(!r.hidden)n++;});document.getElementById('count').textContent=n+'/${plan.cases.length} ca';}['phase','state','level'].forEach(id=>document.getElementById(id).addEventListener('change',filter));document.getElementById('print').addEventListener('click',()=>window.print());</script></body></html>`;
}
module.exports={render};
if(require.main===module){const out=render(JSON.parse(fs.readFileSync(path.join(ROOT,'docs/09-testing/test-matrix.json'),'utf8'))),file=path.join(ROOT,'ci_cd_testing.html');if(process.argv.includes('--check')){if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==out){console.error('HTML stale: run node scripts/ci/render-plan.cjs');process.exitCode=1;}else console.log('TEST_PLAN_HTML_CURRENT');}else{fs.writeFileSync(file,out,'utf8');console.log('Wrote ci_cd_testing.html');}}
