# Generated by Django 5.2.17 on 2026-10-07 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuidelineVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "version_tag",
                    models.CharField(help_text="Ví dụ: v1", max_length=32, unique=True),
                ),
                ("name", models.CharField(help_text="Tên hiển thị cho phiên bản", max_length=200)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_checksum",
                    models.CharField(
                        help_text="SHA-256 của tệp guideline, dùng cho idempotency",
                        max_length=64,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-loaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GuidelineRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rule_id", models.CharField(help_text="Ví dụ: VEH-01", max_length=32)),
                ("section", models.CharField(help_text="Ví dụ: §2.1", max_length=64)),
                ("content", models.TextField(help_text="Nội dung trích đoạn của rule")),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="guideline.guidelineversion",
                    ),
                ),
            ],
            options={
                "ordering": ["rule_id"],
            },
        ),
        migrations.CreateModel(
            name="RuleMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "error_group",
                    models.CharField(
                        blank=True, default="", help_text="Nhóm lỗi: E1, E2, E3", max_length=16
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True, default="", help_text="Tên lớp: car, truck, …", max_length=64
                    ),
                ),
                (
                    "paired_class",
                    models.CharField(
                        blank=True, default="", help_text="Lớp cặp (nếu có): truck", max_length=64
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="guideline.guidelinerule",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="guideline.guidelineversion",
                    ),
                ),
            ],
            options={
                "ordering": ["error_group", "class_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="guidelinerule",
            constraint=models.UniqueConstraint(
                fields=("version", "rule_id"), name="uq_guideline_rule_version_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="rulemapping",
            constraint=models.UniqueConstraint(
                fields=("version", "error_group", "class_name", "paired_class", "rule"),
                name="uq_rule_mapping_context_rule",
            ),
        ),
    ]
