# Generated by Django 5.2.17 on 2026-10-09 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LedgerUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_id", models.PositiveBigIntegerField(db_index=True)),
                ("engine", models.CharField(max_length=64)),
                ("kind", models.CharField(max_length=16)),
                ("cvat_task_id", models.PositiveBigIntegerField()),
                ("frame_number", models.PositiveIntegerField()),
                ("outcome", models.CharField(default="pending", max_length=16)),
                ("not_checked_reason", models.CharField(blank=True, max_length=24)),
                ("attempts", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "engine", "kind", "cvat_task_id", "frame_number"),
                        name="uniq_ledger_unit",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShardCommit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                ("run_id", models.PositiveBigIntegerField(db_index=True)),
                ("snapshot_id", models.PositiveBigIntegerField()),
                ("engine", models.CharField(max_length=64)),
                ("engine_version", models.CharField(max_length=32)),
                ("shard_index", models.PositiveIntegerField()),
                ("output_sha256", models.CharField(max_length=64)),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("committed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "engine", "shard_index"), name="uniq_shard_per_run_engine"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CandidateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_id", models.PositiveBigIntegerField(db_index=True)),
                ("dedup_key", models.CharField(max_length=64)),
                ("engine", models.CharField(max_length=64)),
                ("engine_version", models.CharField(max_length=32)),
                ("family", models.CharField(max_length=64)),
                ("cvat_task_id", models.PositiveBigIntegerField()),
                ("frame_number", models.PositiveIntegerField()),
                ("anchor", models.JSONField()),
                ("policy_version", models.CharField(max_length=32)),
                ("evidence", models.JSONField()),
                ("evidence_sha256", models.CharField(max_length=64)),
                (
                    "shard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="orchestration.shardcommit",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run_id", "dedup_key"), name="uniq_candidate_dedup"
                    )
                ],
            },
        ),
    ]
