# Generated by Django 5.2.17 on 2026-10-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orchestration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shardcommit",
            name="idempotency_key",
            field=models.CharField(max_length=128),
        ),
        migrations.AddConstraint(
            model_name="shardcommit",
            constraint=models.UniqueConstraint(
                fields=("run_id", "idempotency_key"), name="uniq_shard_key_per_run"
            ),
        ),
    ]
